name: Running Test
run-name: ${{github.actor}} is testing out Github actions

on: [push]

jobs:
    Explorer-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
          - run: echo "The job was triggered by ${{github.event_name}} event"
          - run: echo "This job is now running on ${{runner.os}} server hosted by Github"
          - run: echo "The name of the branch is  ${{github.ref}} and the name of repo is ${{github.repository}}"

          - name: Checkout repository code
            uses: actions/checkout@v5
          
          - run: echo "${{github.repository}} has been cloned to runner"

          - run: echo "The workflow is ready to test your code on the runner"

          - name: List Files in the repo
            run: |
                ls ${{github.workspace}}
          - run: echo "this job's status is ${{job.status}}"